"use client";

import { Panel, Section } from "@/components/ui/layout";
import { ScoreBar, SeverityDot, SeverityLabel } from "@/components/ui/score";
import type { Finding, FindingSeverity, ListingAnalysis, Recommendation } from "@/lib/types";

const SECTION_ORDER = [
  ["title", "Title"],
  ["bullets", "Bullets"],
  ["description", "Description"],
  ["images", "Images"],
  ["completeness", "Completeness"],
  ["social_proof", "Social Proof"],
] as const;

const SEVERITY_ORDER: FindingSeverity[] = ["high", "medium", "low", "info"];

function FindingsList({ findings }: { findings: Finding[] }) {
  if (!findings.length) {
    return <p className="text-sm text-muted-foreground">No findings were generated.</p>;
  }

  return (
    <div className="space-y-6">
      {SEVERITY_ORDER.map((severity) => {
        const items = findings.filter((finding) => finding.severity === severity);
        if (!items.length) {
          return null;
        }
        const heading =
          severity === "high"
            ? "High priority"
            : severity === "medium"
              ? "Medium"
              : severity === "low"
                ? "Low"
                : "Notes";
        return (
          <div key={severity} className="space-y-2">
            <p className="text-xs font-medium text-muted-foreground">{heading}</p>
            <ul className="divide-y divide-border">
              {items.map((finding) => (
                <li key={`${finding.code}-${finding.message}`} className="flex gap-3 py-3 first:pt-0 last:pb-0">
                  <SeverityDot severity={finding.severity} />
                  <div className="min-w-0 space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="text-sm font-medium">{finding.category}</p>
                      <SeverityLabel severity={finding.severity} />
                    </div>
                    <p className="text-sm leading-6 text-muted-foreground">{finding.message}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        );
      })}
    </div>
  );
}

function RecommendationsList({ recommendations }: { recommendations: Recommendation[] }) {
  if (!recommendations.length) {
    return (
      <p className="text-sm text-muted-foreground">
        No deterministic actions were generated for this listing.
      </p>
    );
  }
  return (
    <ol className="space-y-3">
      {recommendations.map((item, index) => (
        <li key={item.code} className="flex gap-3 text-sm leading-6">
          <span className="w-5 shrink-0 tabular-nums text-muted-foreground">{index + 1}.</span>
          <span>{item.message}</span>
        </li>
      ))}
    </ol>
  );
}

export function ListingIntelligence({ analysis }: { analysis: ListingAnalysis }) {
  return (
    <Section
      title="Listing intelligence"
      description={`Deterministic analysis ${analysis.score_version}. Scores are not generated by AI.`}
    >
      <Panel className="p-5">
        <div className="grid gap-8 lg:grid-cols-[11rem_1fr] lg:items-start">
          <div>
            <p className="text-xs text-muted-foreground">Overall listing score</p>
            <p className="mt-1 text-[2rem] font-semibold tabular-nums tracking-tight">
              {analysis.overall_score}
              <span className="text-base font-medium text-muted-foreground"> / 100</span>
            </p>
          </div>
          <div className="space-y-3">
            {SECTION_ORDER.map(([key, label]) => {
              const section = analysis.sections[key];
              return <ScoreBar key={key} label={label} score={section.score} max={section.max_score} />;
            })}
          </div>
        </div>
      </Panel>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel className="p-5">
          <h3 className="mb-4 text-[0.95rem] font-semibold">Findings</h3>
          <FindingsList findings={analysis.findings} />
        </Panel>
        <Panel className="p-5">
          <h3 className="mb-4 text-[0.95rem] font-semibold">Recommended actions</h3>
          <RecommendationsList recommendations={analysis.recommendations} />
        </Panel>
      </div>
    </Section>
  );
}
