"use client";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type {
  AnalysisSection,
  Finding,
  FindingSeverity,
  ListingAnalysis,
  Recommendation,
} from "@/lib/types";

const SECTION_LABELS: Record<string, string> = {
  title: "Title",
  bullets: "Bullets",
  description: "Description",
  images: "Images",
  completeness: "Completeness",
  social_proof: "Social Proof",
};

const SEVERITY_STYLES: Record<FindingSeverity, string> = {
  high: "border-transparent bg-destructive text-destructive-foreground",
  medium: "border-transparent bg-amber-100 text-amber-900",
  low: "border-transparent bg-secondary text-secondary-foreground",
  info: "border-border bg-background text-muted-foreground",
};

const SECTION_ORDER = [
  "title",
  "bullets",
  "description",
  "images",
  "completeness",
  "social_proof",
] as const;

function formatMetric(value: unknown): string {
  if (Array.isArray(value)) {
    return value.length ? value.map(String).join(", ") : "none";
  }
  if (typeof value === "boolean") {
    return value ? "yes" : "no";
  }
  if (value == null) {
    return "—";
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

function metricEntries(section: AnalysisSection): Array<[string, unknown]> {
  return Object.entries(section.metrics).filter(([, value]) => {
    return typeof value !== "object" || Array.isArray(value) || value === null;
  });
}

function FindingsList({ findings }: { findings: Finding[] }) {
  if (!findings.length) {
    return <p className="text-sm text-muted-foreground">No findings were generated.</p>;
  }
  return (
    <ul className="space-y-3">
      {findings.map((finding) => (
        <li key={`${finding.code}-${finding.message}`} className="flex gap-3">
          <Badge className={cn("mt-0.5 uppercase", SEVERITY_STYLES[finding.severity])}>
            {finding.severity}
          </Badge>
          <p className="text-sm leading-6 text-foreground">{finding.message}</p>
        </li>
      ))}
    </ul>
  );
}

function RecommendationsList({ recommendations }: { recommendations: Recommendation[] }) {
  if (!recommendations.length) {
    return (
      <p className="text-sm text-muted-foreground">
        No deterministic actions were generated for this listing.
      </p>
    );
  }
  return (
    <ol className="list-decimal space-y-2 pl-5 text-sm leading-6 text-foreground">
      {recommendations.map((item) => (
        <li key={item.code}>{item.message}</li>
      ))}
    </ol>
  );
}

export function ListingIntelligence({ analysis }: { analysis: ListingAnalysis }) {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader className="space-y-2">
          <p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">
            Listing Intelligence
          </p>
          <CardTitle className="text-2xl">Overall Score</CardTitle>
        </CardHeader>
        <CardContent className="space-y-5">
          <p className="text-4xl font-semibold tracking-tight">
            {analysis.overall_score}
            <span className="text-lg font-medium text-muted-foreground"> / 100</span>
          </p>
          <p className="text-xs text-muted-foreground">
            Deterministic analysis {analysis.score_version}. Scores are not generated by AI.
          </p>
          <div className="divide-y divide-border rounded-lg border border-border">
            {SECTION_ORDER.map((key) => {
              const section = analysis.sections[key];
              return (
                <details key={key} className="group p-4">
                  <summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm font-medium">
                    <span>{SECTION_LABELS[key]}</span>
                    <span className="font-mono text-muted-foreground">
                      {section.score}/{section.max_score}
                    </span>
                  </summary>
                  <div className="mt-3 space-y-3 text-sm">
                    <p className="capitalize text-muted-foreground">Status: {section.status}</p>
                    <dl className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                      {metricEntries(section).map(([name, value]) => (
                        <div key={name}>
                          <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                            {name.replaceAll("_", " ")}
                          </dt>
                          <dd className="font-medium">{formatMetric(value)}</dd>
                        </div>
                      ))}
                    </dl>
                    {section.findings.length ? (
                      <ul className="list-disc space-y-1 pl-5 text-muted-foreground">
                        {section.findings.map((note) => (
                          <li key={note}>{note}</li>
                        ))}
                      </ul>
                    ) : null}
                  </div>
                </details>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Key Findings</CardTitle>
        </CardHeader>
        <CardContent>
          <FindingsList findings={analysis.findings} />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recommended Actions</CardTitle>
        </CardHeader>
        <CardContent>
          <RecommendationsList recommendations={analysis.recommendations} />
        </CardContent>
      </Card>
    </div>
  );
}
